export interface ChallengeDefinition {
  id: number;
  code: string;
  title: string;
  description: string;
  category: 'General' | 'Health' | 'Fitness' | 'Productivity' | 'Study' | 'Mindfulness';
  color: string;
  icon: string;
  duration_days: number;
  xp_reward: number;
  badge_name: string;
  is_strict: boolean;
  rule_description: string;
  target_category?: string;
  target_time_of_day?: string;
}

export const INITIAL_CHALLENGES: ChallengeDefinition[] = [
  {
    id: 1,
    code: '7-day-consistency',
    title: '7-Day Consistency Sprint',
    description: 'Complete at least one scheduled habit every day for 7 consecutive days to spark rapid momentum.',
    category: 'General',
    color: '#6C5CE7',
    icon: 'zap',
    duration_days: 7,
    xp_reward: 150,
    badge_name: 'Consistency Initiate',
    is_strict: false,
    rule_description: 'Log any scheduled habit every day. Grace period allows catchup before challenge end.',
  },
  {
    id: 2,
    code: '14-day-discipline',
    title: '14-Day Discipline Sprint',
    description: 'Execute your core daily routines without missing a day for two full weeks.',
    category: 'Productivity',
    color: '#3B82F6',
    icon: 'shield',
    duration_days: 14,
    xp_reward: 350,
    badge_name: 'Discipline Vanguard',
    is_strict: true,
    rule_description: 'STRICT: Complete all scheduled daily habits every single day without interruption.',
  },
  {
    id: 3,
    code: '21-day-habit-builder',
    title: '21-Day Neural Habit Builder',
    description: 'Forge permanent neural pathways with 21 days of continuous daily discipline.',
    category: 'General',
    color: '#8B5CF6',
    icon: 'brain',
    duration_days: 21,
    xp_reward: 500,
    badge_name: 'Neural Architect',
    is_strict: false,
    rule_description: 'Accumulate 21 completed days across your active habits before the sprint deadline.',
  },
  {
    id: 4,
    code: '30-day-no-zero-days',
    title: '30-Day No-Zero-Days Quest',
    description: 'Never allow a single zero day. Complete at least one key priority habit every single calendar day for a full month.',
    category: 'Productivity',
    color: '#EC4899',
    icon: 'flame',
    duration_days: 30,
    xp_reward: 800,
    badge_name: 'Unstoppable Momentum',
    is_strict: true,
    rule_description: 'STRICT: Zero days permitted. If any calendar day has 0 completions, the quest breaks and fails.',
  },
  {
    id: 5,
    code: 'early-riser',
    title: 'Early Riser Challenge',
    description: 'Win the morning by executing your morning routines before 8:00 AM for 14 straight days.',
    category: 'Productivity',
    color: '#FFB547',
    icon: 'sun',
    duration_days: 14,
    xp_reward: 400,
    badge_name: 'Dawn Conqueror',
    is_strict: true,
    target_time_of_day: 'morning',
    rule_description: 'STRICT: Execute your morning-scheduled routine each day unbroken.',
  },
  {
    id: 6,
    code: 'digital-detox',
    title: 'Digital Detox & Mindful Focus',
    description: 'Protect your mental bandwidth by executing daily screen-free mindfulness and reflection for 7 days.',
    category: 'Mindfulness',
    color: '#10B981',
    icon: 'sparkles',
    duration_days: 7,
    xp_reward: 250,
    badge_name: 'Mindful Guardian',
    is_strict: true,
    target_category: 'Mindfulness',
    rule_description: 'STRICT: Log your mindfulness or reflection routine every day without skipping.',
  },
  {
    id: 7,
    code: 'deep-work',
    title: 'Deep Work Mastery Sprint',
    description: 'Execute deep focused work sessions every day for 21 days to achieve breakthrough professional output.',
    category: 'Productivity',
    color: '#6366F1',
    icon: 'target',
    duration_days: 21,
    xp_reward: 600,
    badge_name: 'Deep Work Master',
    is_strict: true,
    target_category: 'Productivity',
    rule_description: 'STRICT: Log focused work/study habits every day with zero missed days.',
  },
  {
    id: 8,
    code: 'workout-consistency',
    title: 'Iron Consistency: Workout Sprint',
    description: 'Log active physical movement, gym workouts, or fitness training consistently for 4 weeks.',
    category: 'Fitness',
    color: '#F97316',
    icon: 'activity',
    duration_days: 28,
    xp_reward: 750,
    badge_name: 'Iron Forger',
    is_strict: true,
    target_category: 'Fitness',
    rule_description: 'STRICT: Log at least one fitness session on every scheduled active day.',
  },
  {
    id: 9,
    code: 'reading-challenge',
    title: '14-Day Reading Challenge',
    description: 'Read at least 15 minutes or 10 pages daily to broaden your mind and compound knowledge.',
    category: 'Study',
    color: '#06B6D4',
    icon: 'book',
    duration_days: 14,
    xp_reward: 300,
    badge_name: 'Master Reader',
    is_strict: false,
    target_category: 'Study',
    rule_description: 'Complete daily reading sessions across 14 days.',
  },
  {
    id: 10,
    code: 'water-intake',
    title: 'Hydration 2L Odyssey',
    description: 'Drink at least 2 liters of water daily to maintain peak hydration and sustained physiological stamina.',
    category: 'Health',
    color: '#0EA5E9',
    icon: 'droplet',
    duration_days: 14,
    xp_reward: 250,
    badge_name: 'Hydro Champion',
    is_strict: false,
    target_category: 'Health',
    rule_description: 'Hit your daily hydration targets for 14 calendar days.',
  },
  {
    id: 11,
    code: 'meditation-mindfulness',
    title: '10-Day Meditation & Stillness',
    description: 'Cultivate emotional poise and inner stillness with 10 days of intentional mindfulness practice.',
    category: 'Mindfulness',
    color: '#14B8A6',
    icon: 'heart',
    duration_days: 10,
    xp_reward: 300,
    badge_name: 'Zen Master',
    is_strict: false,
    target_category: 'Mindfulness',
    rule_description: 'Log daily stillness or meditation sessions for 10 days.',
  },
  {
    id: 12,
    code: 'custom-challenge',
    title: '30-Day Custom Mastery Sprint',
    description: 'Dedicate 30 days of focused effort to your personal priority habit and forge mastery.',
    category: 'General',
    color: '#84CC16',
    icon: 'trophy',
    duration_days: 30,
    xp_reward: 750,
    badge_name: 'Self-Forged Master',
    is_strict: false,
    rule_description: 'Complete your chosen priority habits consistently over 30 days.',
  },
];
